version: '2'

services:
  elasticsearch:
    build: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  auditorium:
    image: auditorium:snapshot
    ports:
      - 8080:8080
